config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :reviews, only: [:show, :index, :new, :create, :destroy] 
    
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'trail_search', to: 'trails#searchpage'
    get 'find_trails', to: 'trails#lookup'
    post 'find_trails', to: 'trails#create'
    resources :trails, only: [:show, :index]
end

app/models/trail.rb
require 'net/http'
require 'json'
class Trail < ApplicationRecord
    
    has_many :reviews
    
    def self.new_lookup(searchparams)
        
        valid_categories = ['primaryname', 'designateduses', 'recreationarea']
        
        searchstring = ""
        valid_categories.each do |category|
            if searchparams[category].length() > 0
                if searchstring.length() > 0
                    searchstring += " AND "
                end
                searchstring += "#{category} LIKE '%#{searchparams[category].downcase().titleize()}%'"
            end
        end
        #if not (valid_categories.include? category)
        #    raise "Invalid search category"
        #end
        
        params = {}
        @api_key = Rails.application.credentials.agrc[:server_agrc_key]
        
        #AGRC stores primaryname as spaced capitalized words EG 'Devils Castle Trail'
        params['predicate'] = searchstring
        params['apiKey'] = @api_key
        
        api_url = "https://api.mapserv.utah.gov/api/v1/search/recreation.trails_and_pathways/primaryname, xid, hikedifficulty, bikedifficulty, designateduses, recreationarea"
    
        uri = URI(URI.encode(api_url))
        uri.query = URI.encode_www_form(params)
        #puts(uri)
        res = Net::HTTP.get_response(uri)
        raise AGRCGeocoderException.new("Received HTTP status #{res.code}") if res.code.to_i != 200
    
        obj = JSON.parse(res.body)
        raise AGRCGeocoderException.new(obj['message']) if obj['status'] != 200
        puts obj
        
        trails = []
        obj['result'].each() do |trail|
            newTrail = {
              :primaryname => trail['attributes']['primaryname'],
              :xid => trail['attributes']['xid'],
              :hikedifficulty => trail['attributes']['hikedifficulty'],
              :bikedifficulty => trail['attributes']['bikedifficulty'],
              :designateduses => trail['attributes']['designateduses'],
              :recreationarea => trail['attributes']['recreationarea']
            }
            trails.append(newTrail)
        end

        #there are tons of copies of the same trails in the API database. Filter them out here
        uniqueTrails = []
        trails.each() do |trail|
            unique = true
            uniqueTrails.each() do |uniqueTrail|
                if trail[:primaryname] == uniqueTrail[:primaryname] && trail[:hikedifficulty] == uniqueTrail[:hikedifficulty] && trail[:bikedifficulty] == uniqueTrail[:bikedifficulty] && trail[:designateduses] == uniqueTrail[:designateduses] && trail[:recreationarea] == uniqueTrail[:recreationarea]
                    unique = false
                    break
                end
            end
            if unique
                uniqueTrails.append(trail)
            end
        end

        return uniqueTrails
    end
    
    class AGRCGeocoderException < Exception; end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

    def searchpage
    end

    def lookup
        if params[:primaryname].length > 0 || params[:recreationarea].length > 0 || params[:designateduses].length > 0
            @trails = Trail.new_lookup(params)
        else
            flash[:alert] = "Please enter search criteria"
            redirect_to trail_search_path
        end
    end

    def create
        @trail =  Trail.find_by(xid: params[:trail][:xid])
        if not @trail
            @trail = Trail.new(trail_params())
            @trail.rating = 0
            if @trail.save()
                #flash[:notice] = "You are the first to view " + @trail.primaryname + ", A profile for this trail has been generated."
            else
                flash[:alert] = "The profile for the trail was not successfully generated."
            end
        end
        redirect_to trail_path(@trail.id)
    end

    def show
        @trail = Trail.find(params[:id])
        revs = @trail.reviews
        totalRating = 0
        revs.each do |rev|
            totalRating += rev.rating
        end
        avgRating = totalRating.to_d / @trail.reviews.count.to_d
        @trail.rating = avgRating
        @trail.save

        @reviews = @trail.reviews.paginate(page: params[:page], per_page: 5)
    end

private

def trail_params
    params.require(:trail).permit(:primaryname, :xid, :hikedifficulty, :bikedifficulty, :designateduses, :recreationarea)
end


end

app/views/trails/lookup.html.erb
<div id="page-content">
<% if @trails.length() > 0 %>
    <% @trails.each do |trail|%>
        <div class="card m-3 p-3">
            <% if trail[:primaryname]%>
                <strong>Trail Name: </strong> <%= trail[:primaryname]%>
            <% end %>

            <% if trail[:hikedifficulty]%>
                <strong>Hike Difficulty: </strong> <%= trail[:hikedifficulty]%>
            <% end %>
            <% if trail[:bikedifficulty]%>
                <strong>Bike Difficulty: </strong> <%= trail[:bikedifficulty]%>
            <% end %>
            <% if trail[:designateduses]%>
                <strong>Type: </strong> <%= trail[:designateduses]%>
            <% end %>
            <% if trail[:recreationarea]%>
                <strong>Location: </strong> <%= trail[:recreationarea]%>
            <% end %>
            <div class="mt-3 mb-0 row">
                <div class = "col-10">
                    <%= link_to "View this trail.", find_trails_path(trail: trail), class: "btn btn-primary", method: :post%>
                </div>
            </div>
        </div>
    <% end %>
<% else %>
    <div class="container bg-light p-2 my-3 rounded">
        <h2 class="text-center my-4"> No Trails found with specified parameters </h2>
        <div class="row justify-content-center">
            <%= link_to "Return to Search", trail_search_path, class: "btn btn-primary" %>
        </div>
    </div>
<% end %>
</div>

app/views/trails/searchpage.html.erb
<div id="page-content">
<div class='m-3 text-center'>
    <h1>Trails Search</h1>
</div>
<div class="container">
<div class="row justify-content-center">

<div class="m-3 col-10 bg-dark rounded">
    <%= form_tag find_trails_path, method: :get do %>
        <div class="my-4 form-group row justify-content-center">
            <div class="col-sm-11 pr-0">
                <%= text_field_tag :primaryname, params[:primaryname], placeholder: "name of trail", autofocus: true, class: "form-control form-control-lg"%>
            </div>
        </div>

        <div class="my-4 form-group row justify-content-center">
            <div class="col-sm-11 pr-0">
                <%= text_field_tag :recreationarea, params[:recreationarea], placeholder: "recreation area ex. 'Zion'", autofocus: true, class: "form-control form-control-lg"%>
            </div>
        </div>

        <label for="designateduses" class="text-white text-center mb-0 pb-0"> Type of Trail: </label>

        <div class="mb-4 mt-2 form-group row justify-content-center">
            <div class="mb-3 row">
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <div class="btn rounded btn-secondary m-2">
                        All
                        <%= radio_button_tag :designateduses, "", checked = true, class: "form-control form-control-lg" %>          
                    </div>
                    <div class="btn rounded btn-secondary m-2">
                        Pedestrian
                        <%= radio_button_tag :designateduses, "Pedestrian", checked = false, class: "form-control form-control-lg" %>          
                    </div>
                    <div class="btn rounded btn-secondary m-2">
                        Bike
                        <%= radio_button_tag :designateduses, "Bike", checked = false, class: "form-control form-control-lg" %>          
                    </div>
                    <div class="btn rounded btn-secondary m-2">
                        Multiuse
                        <%= radio_button_tag :designateduses, "Multiuse", checked = false, class: "form-control form-control-lg" %>                      
                    </div>
                </div>
            </div>
        </div>

        <div class="my-4 form-group row justify-content-center">
            <%= button_tag type: :submit, class: "btn btn-primary" do%>
            <%= 'Search!' %>
            <% end %>
        </div>
    <% end %>
</div>
</div>
</div>
</div>

app/views/trails/show.html.erb
<div id="page-content">
    <div class="container">
        <div class="row justify-content-md-center mt-4">
            <div class="col-8">
                <div class="card shadow" style="width: 100%;">
                    <div class="card-header text-center">
                        <h2><%= @trail.primaryname %></h2>
                        <div class="row justify-content-center">
                            <% i = 1 %>
                            <% while i < 6%>
                                <% if i <= @trail.rating %>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                    </svg>
                                <% else %>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                                    <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                    </svg>
                                <% end %>
                                <% i += 1 %>
                            <% end %>
                        </div>
                        <p><small><%=  "(" + @trail.rating.to_s + " Based on " + pluralize(@trail.reviews.count, "Review") +".)" %></small></p>                       
                    </div>
                    <div class="card-body">
                        <h5 class="text-center">Info</h5> 
                        <div class="row">
                            <% if @trail[:primaryname]%>
                                <strong>Trail Name: </strong> <%= @trail[:primaryname]%>
                            <% end %>
                        </div>
                        <div class="row">
                            <% if @trail[:hikedifficulty].length > 0%>
                                <strong>Hike Difficulty: </strong> <%= @trail[:hikedifficulty]%>
                            <% end %>
                        </div>
                        <div class="row">
                            <% if @trail[:bikedifficulty].length > 0%>
                                <strong>Bike Difficulty: </strong> <%= @trail[:bikedifficulty]%>
                            <% end %>
                        </div>
                        <div class="row">
                            <% if @trail[:designateduses].length > 0%>
                                <strong>Type: </strong> <%= @trail[:designateduses]%>
                            <% end %>
                        </div>
                        <div class="row">
                            <% if @trail[:recreationarea].length > 0%>
                                <strong>Location: </strong> <%= @trail[:recreationarea]%>
                            <% end %>
                        </div>
                     </div>
                </div>
                <div class = "container row p-3 justify-content-left">
                    <%= link_to 'Review this trail', new_review_path(trail: @trail), class: "m-3 btn btn-success" %>
                    <%= link_to 'Return to trail search', trail_search_path, class: "m-3 btn btn-primary" %>
                </div>              
            </div>
        </div>
    </div>
    <div class="apple_pagination">
        <%= will_paginate @reviews, :container => false %>
    </div>

    <%= render 'reviews/review', obj: @reviews %>

    <div class="apple_pagination mb-5 mt-4">
        <%= will_paginate @reviews, :container => false %>
    </div>    
</div>