config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :reviews, only: [:show, :index, :new, :create, :destroy] 
    
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'trail_search', to: 'trails#searchpage'
    get 'find_trails', to: 'trails#lookup'
    post 'find_trails', to: 'trails#create'
    resources :trails, only: [:show, :index]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_review, only: [:show, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:destroy]

    def show
    end

    def index
        @reviews = Review.paginate(page: params[:page], per_page: 10)
    end
    
    def new
        @review = Review.new()
        @trail = params[:trail]
    end
    
    def create
        @review = Review.new(review_params())
        @review.user = current_user
        
        if @review.save()
            flash[:notice] = "Review Posted Successfully."

            trail = Trail.find(@review.trail_id)
            revs = trail.reviews
            totalRating = 0
            revs.each do |rev|
                totalRating += rev.rating
            end
            avgRating = totalRating.to_d / trail.reviews.count.to_d
            trail.rating = avgRating
            if trail.save()
                flash[:notice] = "Trail Rating Adjusted"
            else
                flash[:alert] = "Trail Rating out-of-date"
            end

            redirect_to review_path(@review)
        else
            @trail = @review.trail_id
            render 'new'
        end
    end
    
    def destroy
        @review.destroy()
        redirect_to reviews_path
    end
    
    private 

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :body, :rating, :trail_id)
  end

  def require_same_user
      if current_user.id != @review.user.id && !current_user.admin?
          flash[:alert] = "You can only delete your own reviews."
          redirect_to @review
      end
  end

end

app/views/reviews/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
        <%= render 'shared/errors', obj: @review %>
        <%= form_with(model: @review, class: "shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>
        <div class="mb-3 row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of review" %>
          </div>
        </div>
        <div class="mb-3 row">
          <%= f.label :body, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :body, rows: 10, class: "form-control shadow rounded", placeholder: "Review body goes here." %>
          </div>
        </div>
        <div class="mb-3 row">
          <%= f.label :rating, "Overall Health of Trail:", class: "col-3 col-form-label text-light p-3" %>          
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <div class = "btn btn-danger">
              <%= f.label :rating_1, "Terrible!", class: "text-white p-2"%>
              <%= f.radio_button :rating, 1, class: "form-control p-2"%>
            </div>
            <div class = "btn btn-secondary">
              <%= f.radio_button :rating, 2, class: "form-control p-2"%>
              <%= f.label :rating_2, "Poor.", class: "text-white p-2"%>
            </div>
            <div class = "btn btn-warning">
              <%= f.radio_button :rating, 3, class: "form-control p-2"%>
              <%= f.label :rating_3, "Okay.", class: "text-white p-2"%>
            </div>
            <div class = "btn btn-success">
              <%= f.radio_button :rating, 4, class: "form-control p-2"%>
              <%= f.label :rating_4, "Good.", class: "text-white p-2"%>
            </div>
            <div class = "btn btn-info">
              <%= f.radio_button :rating, 5, class: "form-control p-2"%>
              <%= f.label :rating_5, "Great!", class: " text-white p-2"%>
            </div>
          </div>
        </div> 
        <%= f.hidden_field(:trail_id, value: @trail) %>       
        <div class="row mb-3 justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg col-3" %>
        </div>
      <% end %>
    </div>
    <%= link_to ' Cancel and return to trail ', trail_path(@trail), class: "btn btn-primary col-4 text-center" %>
  </div>
</div> 

app/views/reviews/_review.html.erb
<div class="container">
        <% obj.each do |review| %>
                <div class="row justify-content-md-center mt-4">
                    <div class="col-8">
                        <div class="card shadow" style="width: 100%;">
                          <div class="card-body">
                            <h4 class = "card-header text-center font-weight-bold"><%= review.trail.primaryname %></h4>
                            <h5 class="card-title text-center m-2 text-decoration-underline"><u><%= link_to review.title, review_path(review.id) %></u></h5>
                            <div class = "row justify-content-center">
                                <% i = 1 %>
                                <% while i < 6 %>
                                    <% if i <= review.rating %>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                        </svg>
                                    <% else %>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                                        <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                        </svg>
                                    <% end %>
                                    <% i += 1 %>
                                <% end %>
                            </div>
                            <p class="card-text mt-3"><%= truncate(review.body, length: 100) %></p>
                            <div class="row justify-content-center">
                                <%= link_to "Go to Review", review_path(review.id), class: "btn btn-primary" %>
                            </div>
                          </div>
                          <div class="card-footer text-muted">
                              <small> Created <%= time_ago_in_words(review.created_at) %> ago by <%= link_to review.user.username, user_path(review.user.id) %></small>
                          </div>
                        </div>
                    </div>
                </div>
        <% end %> 
    </div>

app/views/reviews/index.html.erb
<div id="page-content">
    <h1 class="text-center mb-4 mt-4">Reviews</h1>
    
    <div class="apple_pagination">
        <%= will_paginate @reviews, :container => false %>
    </div>
    
    <%= render 'review', obj: @reviews %>
    
    <div class="apple_pagination mb-5 mt-4">
        <%= will_paginate @reviews, :container => false %>
    </div>    
</div>

app/views/reviews/new.html.erb
<div id="page-content">
    

    <h1 class="text-center mt-4">Submit a new review!</h1>
    
    <%= render 'form' %>

</div>

app/views/reviews/show.html.erb
<div id="page-content">
    <div class="container">
        <div class="row justify-content-md-center mt-4">
            <div class="col-8">
                <div class="card shadow" style="width: 100%;">
                    <div class="card-header text-center">
                        <h2><%= @review.title %></h2>
                        <div class="row justify-content-center">
                            <% i = 1 %>
                            <% while i < 6%>
                                <% if i <= @review.rating %>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                    </svg>
                                <% else %>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                                    <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                    </svg>
                                <% end %>
                                <% i += 1 %>
                            <% end %>
                        </div>
                        <small class="text-muted"> Created <%= time_ago_in_words(@review.created_at) %> ago by <%= link_to @review.user.username, user_path(@review.user)%></small>
                        <%= link_to gravatar_for(@review.user, size: 40), user_path(@review.user.id)%>
                    </div>
                    <div class="card-body">
                        <div class = "row justify-content-center">
                        <h5 class="text-center mr-4"><%= link_to "Trail: " + @review.trail.primaryname, trail_path(@review.trail.id)%></h5>    
                        <% i = 1 %>
                        <% while i < 6%>
                            <% if i <= @review.trail.rating %>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                </svg>
                            <% else %>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                                <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                </svg>
                            <% end %>
                            <% i += 1 %>
                        <% end %>
                        <p><small><%= "(" + @review.trail.rating.to_s + " Based on " + pluralize(@review.trail.reviews.count, "Review") +".)" %></small></p>
                        </div>  
                        <p class="card-text"><%= simple_format(@review.body) %></p>
                     </div>
                </div>
                <div class = "container row p-3 justify-content-left">
                    <%= link_to 'Return to Trail Search', trail_search_path, class: "m-3 btn btn-primary" %>
                    <% if logged_in? && (@review.user.id == current_user.id || current_user.admin?) %>
                        <%= link_to "Delete", review_path(@review), class:"m-3 btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>