config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :reviews, only: [:show, :index, :new, :create, :destroy] 
    
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'trail_search', to: 'trails#searchpage'
    get 'find_trails', to: 'trails#lookup'
    post 'find_trails', to: 'trails#create'
    resources :trails, only: [:show, :index]
end

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
    <% if name == "notice" %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= msg %>
      </div>
    <% else %>
      <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
        <%= msg %>
      </div>
    <% end %>
  <% end %> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>           

        <li class="nav-item">
          <%= link_to "Find a Trail", trail_search_path, class: "nav-link" %>
        </li>                
        
        <li class="nav-item">
          <%= link_to "Reviewers", users_path, class: "nav-link" %>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "~(Admin)~" if current_user.admin? %> Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
          </div>         
          <li class="nav-item">
            <%= link_to 'Log out', logout_path, class: 'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', signup_path , class: 'nav-link' %>
          </li>            
        <% end %>
      </ul>
    </div>
  </div>
  <div class="navbar-brand">    <%= link_to "UTAH TRAIL REVIEW", root_path, class: "navbar-brand", id: "logo" %></div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UtahTrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column" id="wholePage">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>